// class for each color
const colorThemeLight = {
  red: {
    bg: "bg-red-50",
    bgDark: "bg-red-700",
    bgMedium: "bg-red-500",
    bgLight: "bg-red-300",
    bgExtraLight: "bg-red-100",
    border: "border-red-100",
    text: "text-red-700",
    subtext: "text-red-500",
    iconBg: "bg-red-100",
    iconText: "text-red-600",
    hoverBgExtraLight: "hover:bg-red-100",
  },
  orange: {
    bg: "bg-orange-50",
    bgDark: "bg-orange-700",
    bgMedium: "bg-orange-500",
    bgLight: "bg-orange-300",
    bgExtraLight: "bg-orange-100",
    border: "border-orange-100",
    text: "text-orange-700",
    subtext: "text-orange-500",
    iconBg: "bg-orange-100",
    iconText: "text-orange-600",
    hoverBgExtraLight: "hover:bg-orange-100",
  },
  amber: {
    bg: "bg-amber-50",
    bgDark: "bg-amber-700",
    bgMedium: "bg-amber-500",
    bgLight: "bg-amber-300",
    bgExtraLight: "bg-amber-100",
    border: "border-amber-100",
    text: "text-amber-700",
    subtext: "text-amber-500",
    iconBg: "bg-amber-100",
    iconText: "text-amber-600",
    hoverBgExtraLight: "hover:bg-amber-100",
  },
  yellow: {
    bg: "bg-yellow-50",
    bgDark: "bg-yellow-700",
    bgMedium: "bg-yellow-500",
    bgLight: "bg-yellow-300",
    bgExtraLight: "bg-yellow-100",
    border: "border-yellow-100",
    text: "text-yellow-700",
    subtext: "text-yellow-500",
    iconBg: "bg-yellow-100",
    iconText: "text-yellow-600",
    hoverBgExtraLight: "hover:bg-yellow-100",
  },
  lime: {
    bg: "bg-lime-50",
    bgDark: "bg-lime-700",
    bgMedium: "bg-lime-500",
    bgLight: "bg-lime-300",
    bgExtraLight: "bg-lime-100",
    border: "border-lime-100",
    text: "text-lime-700",
    subtext: "text-lime-500",
    iconBg: "bg-lime-100",
    iconText: "text-lime-600",
    hoverBgExtraLight: "hover:bg-lime-100",
  },
  green: {
    bg: "bg-green-50",
    bgDark: "bg-green-700",
    bgMedium: "bg-green-500",
    bgLight: "bg-green-300",
    bgExtraLight: "bg-green-100",
    border: "border-green-100",
    text: "text-green-700",
    subtext: "text-green-500",
    iconBg: "bg-green-100",
    iconText: "text-green-600",
    hoverBgExtraLight: "hover:bg-green-100",
  },
  emerald: {
    bg: "bg-emerald-50",
    bgDark: "bg-emerald-700",
    bgMedium: "bg-emerald-500",
    bgLight: "bg-emerald-300",
    bgExtraLight: "bg-emerald-100",
    border: "border-emerald-100",
    text: "text-emerald-700",
    subtext: "text-emerald-500",
    iconBg: "bg-emerald-100",
    iconText: "text-emerald-600",
    hoverBgExtraLight: "hover:bg-emerald-100",
  },
  teal: {
    bg: "bg-teal-50",
    bgDark: "bg-teal-700",
    bgMedium: "bg-teal-500",
    bgLight: "bg-teal-300",
    bgExtraLight: "bg-teal-100",
    border: "border-teal-100",
    text: "text-teal-700",
    subtext: "text-teal-500",
    iconBg: "bg-teal-100",
    iconText: "text-teal-600",
    hoverBgExtraLight: "hover:bg-teal-100",
  },
  cyan: {
    bg: "bg-cyan-50",
    bgDark: "bg-cyan-700",
    bgMedium: "bg-cyan-500",
    bgLight: "bg-cyan-300",
    bgExtraLight: "bg-cyan-100",
    border: "border-cyan-100",
    text: "text-cyan-700",
    subtext: "text-cyan-500",
    iconBg: "bg-cyan-100",
    iconText: "text-cyan-600",
    hoverBgExtraLight: "hover:bg-cyan-100",
  },
  sky: {
    bg: "bg-sky-50",
    bgDark: "bg-sky-700",
    bgMedium: "bg-sky-500",
    bgLight: "bg-sky-300",
    bgExtraLight: "bg-sky-100",
    border: "border-sky-100",
    text: "text-sky-700",
    subtext: "text-sky-500",
    iconBg: "bg-sky-100",
    iconText: "text-sky-600",
    hoverBgExtraLight: "hover:bg-sky-100",
  },
  blue: {
    bg: "bg-blue-50",
    bgDark: "bg-blue-700",
    bgMedium: "bg-blue-500",
    bgLight: "bg-blue-300",
    bgExtraLight: "bg-blue-100",
    border: "border-blue-100",
    text: "text-blue-700",
    subtext: "text-blue-500",
    iconBg: "bg-blue-100",
    iconText: "text-blue-600",
    hoverBgExtraLight: "hover:bg-blue-100",
  },
  indigo: {
    bg: "bg-indigo-50",
    bgDark: "bg-indigo-700",
    bgMedium: "bg-indigo-500",
    bgLight: "bg-indigo-300",
    bgExtraLight: "bg-indigo-100",
    border: "border-indigo-100",
    text: "text-indigo-700",
    subtext: "text-indigo-500",
    iconBg: "bg-indigo-100",
    iconText: "text-indigo-600",
    hoverBgExtraLight: "hover:bg-indigo-100",
  },
  violet: {
    bg: "bg-violet-50",
    bgDark: "bg-violet-700",
    bgMedium: "bg-violet-500",
    bgLight: "bg-violet-300",
    bgExtraLight: "bg-violet-100",
    border: "border-violet-100",
    text: "text-violet-700",
    subtext: "text-violet-500",
    iconBg: "bg-violet-100",
    iconText: "text-violet-600",
    hoverBgExtraLight: "hover:bg-violet-100",
  },
  purple: {
    bg: "bg-purple-50",
    bgDark: "bg-purple-700",
    bgMedium: "bg-purple-500",
    bgLight: "bg-purple-300",
    bgExtraLight: "bg-purple-100",
    border: "border-purple-100",
    text: "text-purple-700",
    subtext: "text-purple-500",
    iconBg: "bg-purple-100",
    iconText: "text-purple-600",
    hoverBgExtraLight: "hover:bg-purple-100",
  },
  fuchsia: {
    bg: "bg-fuchsia-50",
    bgDark: "bg-fuchsia-700",
    bgMedium: "bg-fuchsia-500",
    bgLight: "bg-fuchsia-300",
    bgExtraLight: "bg-fuchsia-100",
    border: "border-fuchsia-100",
    text: "text-fuchsia-700",
    subtext: "text-fuchsia-500",
    iconBg: "bg-fuchsia-100",
    iconText: "text-fuchsia-600",
    hoverBgExtraLight: "hover:bg-fuchsia-100",
  },
  pink: {
    bg: "bg-pink-50",
    bgDark: "bg-pink-700",
    bgMedium: "bg-pink-500",
    bgLight: "bg-pink-300",
    bgExtraLight: "bg-pink-100",
    border: "border-pink-100",
    text: "text-pink-700",
    subtext: "text-pink-500",
    iconBg: "bg-pink-100",
    iconText: "text-pink-600",
    hoverBgExtraLight: "hover:bg-pink-100",
  },
  rose: {
    bg: "bg-rose-50",
    bgDark: "bg-rose-700",
    bgMedium: "bg-rose-500",
    bgLight: "bg-rose-300",
    bgExtraLight: "bg-rose-100",
    border: "border-rose-100",
    text: "text-rose-700",
    subtext: "text-rose-500",
    iconBg: "bg-rose-100",
    iconText: "text-rose-600",
    hoverBgExtraLight: "hover:bg-rose-100",
  },
  slate: {
    bg: "bg-slate-50",
    bgDark: "bg-slate-700",
    bgMedium: "bg-slate-500",
    bgLight: "bg-slate-300",
    bgExtraLight: "bg-slate-100",
    border: "border-slate-100",
    text: "text-slate-700",
    subtext: "text-slate-500",
    iconBg: "bg-slate-100",
    iconText: "text-slate-600",
    hoverBgExtraLight: "hover:bg-slate-100",
  },
  zinc: {
    bg: "bg-zinc-50",
    bgDark: "bg-zinc-700",
    bgMedium: "bg-zinc-500",
    bgLight: "bg-zinc-300",
    bgExtraLight: "bg-zinc-100",
    border: "border-zinc-100",
    text: "text-zinc-700",
    subtext: "text-zinc-500",
    iconBg: "bg-zinc-100",
    iconText: "text-zinc-600",
    hoverBgExtraLight: "hover:bg-zinc-100",
  },
  stone: {
    bg: "bg-stone-50",
    bgDark: "bg-stone-700",
    bgMedium: "bg-stone-500",
    bgLight: "bg-stone-300",
    bgExtraLight: "bg-stone-100",
    border: "border-stone-100",
    text: "text-stone-700",
    subtext: "text-stone-500",
    iconBg: "bg-stone-100",
    iconText: "text-stone-600",
    hoverBgExtraLight: "hover:bg-stone-100",
  },
  taupe: {
    bg: "bg-taupe-50",
    bgDark: "bg-taupe-700",
    bgMedium: "bg-taupe-500",
    bgLight: "bg-taupe-300",
    bgExtraLight: "bg-taupe-100",
    border: "border-taupe-100",
    text: "text-taupe-700",
    subtext: "text-taupe-500",
    iconBg: "bg-taupe-100",
    iconText: "text-taupe-600",
    hoverBgExtraLight: "hover:bg-taupe-100",
  },
  mauve: {
    bg: "bg-mauve-50",
    bgDark: "bg-mauve-700",
    bgMedium: "bg-mauve-500",
    bgLight: "bg-mauve-300",
    bgExtraLight: "bg-mauve-100",
    border: "border-mauve-100",
    text: "text-mauve-700",
    subtext: "text-mauve-500",
    iconBg: "bg-mauve-100",
    iconText: "text-mauve-600",
    hoverBgExtraLight: "hover:bg-mauve-100",
  },
};

/**
 * Looks up a color theme by name, falling back to purple if the key
 * doesn't exist (or there is a typo)
 */
export function getColorTheme(color) {
  return colorThemeLight[color] || colorThemeLight.purple;
}

export default colorThemeLight;
