// class for each color
const colorThemeLight = {
    red: {
        bg: "bg-red-50",
        border: "border-red-100",
        text: "text-red-700",
        subtext: "text-red-500",
        iconBg: "bg-red-100",
        iconText: "text-red-600",
    },
    orange: {
        bg: "bg-orange-50",
        border: "border-orange-100",
        text: "text-orange-700",
        subtext: "text-orange-500",
        iconBg: "bg-orange-100",
        iconText: "text-orange-600",
    },
    amber: {
        bg: "bg-amber-50",
        border: "border-amber-100",
        text: "text-amber-700",
        subtext: "text-amber-500",
        iconBg: "bg-amber-100",
        iconText: "text-amber-600",
    },
    yellow: {
        bg: "bg-yellow-50",
        border: "border-yellow-100",
        text: "text-yellow-700",
        subtext: "text-yellow-500",
        iconBg: "bg-yellow-100",
        iconText: "text-yellow-600",
    },
    lime: {
        bg: "bg-lime-50",
        border: "border-lime-100",
        text: "text-lime-700",
        subtext: "text-lime-500",
        iconBg: "bg-lime-100",
        iconText: "text-lime-600",
    },
    green: {
        bg: "bg-green-50",
        border: "border-green-100",
        text: "text-green-700",
        subtext: "text-green-500",
        iconBg: "bg-green-100",
        iconText: "text-green-600",
    },
    emerald: {
        bg: "bg-emerald-50",
        border: "border-emerald-100",
        text: "text-emerald-700",
        subtext: "text-emerald-500",
        iconBg: "bg-emerald-100",
        iconText: "text-emerald-600",
    },
    teal: {
        bg: "bg-teal-50",
        border: "border-teal-100",
        text: "text-teal-700",
        subtext: "text-teal-500",
        iconBg: "bg-teal-100",
        iconText: "text-teal-600",
    },
    cyan: {
        bg: "bg-cyan-50",
        border: "border-cyan-100",
        text: "text-cyan-700",
        subtext: "text-cyan-500",
        iconBg: "bg-cyan-100",
        iconText: "text-cyan-600",
    },
    sky: {
        bg: "bg-sky-50",
        border: "border-sky-100",
        text: "text-sky-700",
        subtext: "text-sky-500",
        iconBg: "bg-sky-100",
        iconText: "text-sky-600",
    },
    blue: {
        bg: "bg-blue-50",
        border: "border-blue-100",
        text: "text-blue-700",
        subtext: "text-blue-500",
        iconBg: "bg-blue-100",
        iconText: "text-blue-600",
    },
    indigo: {
        bg: "bg-indigo-50",
        border: "border-indigo-100",
        text: "text-indigo-700",
        subtext: "text-indigo-500",
        iconBg: "bg-indigo-100",
        iconText: "text-indigo-600",
    },
    violet: {
        bg: "bg-violet-50",
        border: "border-violet-100",
        text: "text-violet-700",
        subtext: "text-violet-500",
        iconBg: "bg-violet-100",
        iconText: "text-violet-600",
    },
    purple: {
        bg: "bg-purple-50",
        border: "border-purple-100",
        text: "text-purple-700",
        subtext: "text-purple-500",
        iconBg: "bg-purple-100",
        iconText: "text-purple-600",
    },
    fuchsia: {
        bg: "bg-fuchsia-50",
        border: "border-fuchsia-100",
        text: "text-fuchsia-700",
        subtext: "text-fuchsia-500",
        iconBg: "bg-fuchsia-100",
        iconText: "text-fuchsia-600",
    },
    pink: {
        bg: "bg-pink-50",
        border: "border-pink-100",
        text: "text-pink-700",
        subtext: "text-pink-500",
        iconBg: "bg-pink-100",
        iconText: "text-pink-600",
    },
    rose: {
        bg: "bg-rose-50",
        border: "border-rose-100",
        text: "text-rose-700",
        subtext: "text-rose-500",
        iconBg: "bg-rose-100",
        iconText: "text-rose-600",
    },
    slate: {
        bg: "bg-slate-50",
        border: "border-slate-100",
        text: "text-slate-700",
        subtext: "text-slate-500",
        iconBg: "bg-slate-100",
        iconText: "text-slate-600",
    },
    zinc: {
        bg: "bg-zinc-50",
        border: "border-zinc-100",
        text: "text-zinc-700",
        subtext: "text-zinc-500",
        iconBg: "bg-zinc-100",
        iconText: "text-zinc-600",
    },
    stone: {
        bg: "bg-stone-50",
        border: "border-stone-100",
        text: "text-stone-700",
        subtext: "text-stone-500",
        iconBg: "bg-stone-100",
        iconText: "text-stone-600",
    },
    taupe: {
        bg: "bg-taupe-50",
        border: "border-taupe-100",
        text: "text-taupe-700",
        subtext: "text-taupe-500",
        iconBg: "bg-taupe-100",
        iconText: "text-taupe-600",
    },
    mauve: {
        bg: "bg-mauve-50",
        border: "border-mauve-100",
        text: "text-mauve-700",
        subtext: "text-mauve-500",
        iconBg: "bg-mauve-100",
        iconText: "text-mauve-600",
    },
};

/**
 * Looks up a color theme by name, falling back to purple if the key
 * doesn't exist (or there is a typo)
 */
export function getColorTheme(color) {
    return colorThemeLight[color] || colorThemeLight.purple;
}

export default colorThemeLight;