import {
  X,
  UserRound,
  House,
  Home,
  KeyRound,
  Users,
  Sparkles,
  Building,
  PartyPopper,
  Car,
  Bike,
  Footprints,
  TrainFront,
  Accessibility,
  FileText,
  PersonStanding,
  UserPlus,
  Baby,
  Dog,
  CarTaxiFront,
  BriefcaseBusiness,
  Briefcase,
  GraduationCap,
  Laptop,
  Heart,
  Search,
  CreditCard,
  Banknote,
  Hospital,
  StickyNote,
  Wrench,
  Lightbulb,
  Apple,
  Stethoscope,
  PawPrint,
  LibraryBig,
  PiggyBank,
  Gamepad2,
  Zap,
  Droplet,
  Flame,
  Globe,
  Smartphone,
  Trash,
  Tv,
  ShoppingCart,
  Coffee,
  HandPlatter,
  Utensils,
  Glasses,
  Smile,
  Brain,
  BookHeart,
  PillBottle,
  Bandage,
  Bed,
  Ear,
  Wind,
  Pill,
  Shirt,
  Scissors,
  Dumbbell,
  Hand,
  ShieldCheck,
  Tablets,
  Shapes,
  PackageOpen,
  Book,
  PencilLine,
  Backpack,
  University,
  Video,
  Palette,
  Plane,
  RotateCcw,
  Gift,
  Package,
  HeartPlus,
  HeartPulse,
  TriangleAlert,
  HandCoins,
  LineChart,
  SmilePlus,
  Coins,
  CircleDollarSign,
  TrendingUp,
  Umbrella,
  Wallet,
  Sprout,
  Leaf,
  MirrorRound,
  BrushCleaning,
  DollarSign,
  Landmark,
  Ticket,
  Film,
  Receipt,
  Fuel,
  BookOpen,
  TramFront,
  Warehouse,
  LampDesk,
  Armchair,
  Flower,
  Clover,
  Sun,
  Bug,
  School,
  Eraser,
  Hammer,
  Puzzle,
  PencilRuler,
  Music,
  Siren,
  Feather,
  ChefHat,
  Snowflake,
  AirVent,
  Cat,
  TreePalm,
  Dices,
  Bubbles,
  Bird,
  KeySquare,
  Paintbrush,
  Trees,
  Fish,
  SportShoe,
  Bath,
  ThermometerSnowflake,
  Transgender,
  WashingMachine,
  MapPinned,
  ParkingCircle,
  Mail,
  Bus,
  Train,
  Wifi,
  Activity,
  HeartHandshake,
  Shield,
  Bell,
  Clock,
  Calendar,
  Star,
  CheckCircle,
  Gem,
  Egg,
  GlassWater,
} from "lucide-react";

export const ICONS = {
  X: X,
  UserRound: UserRound,
  House: House,
  Home: Home,
  KeyRound: KeyRound,
  Users: Users,
  Sparkles: Sparkles,
  Building: Building,
  PartyPopper: PartyPopper,
  Car: Car,
  Bike: Bike,
  Footprints: Footprints,
  TrainFront: TrainFront,
  Accessibility: Accessibility,
  FileText: FileText,
  PersonStanding: PersonStanding,
  UserPlus: UserPlus,
  Baby: Baby,
  Dog: Dog,
  CarTaxiFront: CarTaxiFront,
  BriefcaseBusiness: BriefcaseBusiness,
  Briefcase: Briefcase,
  GraduationCap: GraduationCap,
  Laptop: Laptop,
  Heart: Heart,
  Search: Search,
  CreditCard: CreditCard,
  Banknote: Banknote,
  Hospital: Hospital,
  StickyNote: StickyNote,
  Wrench: Wrench,
  Lightbulb: Lightbulb,
  Apple: Apple,
  Stethoscope: Stethoscope,
  PawPrint: PawPrint,
  LibraryBig: LibraryBig,
  PiggyBank: PiggyBank,
  Gamepad2: Gamepad2,
  Zap: Zap,
  Droplet: Droplet,
  Flame: Flame,
  Globe: Globe,
  Smartphone: Smartphone,
  Trash: Trash,
  Tv: Tv,
  ShoppingCart: ShoppingCart,
  Coffee: Coffee,
  HandPlatter: HandPlatter,
  Utensils: Utensils,
  Glasses: Glasses,
  Smile: Smile,
  Brain: Brain,
  BookHeart: BookHeart,
  PillBottle: PillBottle,
  Bandage: Bandage,
  Bed: Bed,
  Ear: Ear,
  Wind: Wind,
  Pill: Pill,
  Shirt: Shirt,
  Scissors: Scissors,
  Dumbbell: Dumbbell,
  Hand: Hand,
  ShieldCheck: ShieldCheck,
  Tablets: Tablets,
  Shapes: Shapes,
  PackageOpen: PackageOpen,
  Book: Book,
  PencilLine: PencilLine,
  Backpack: Backpack,
  University: University,
  Video: Video,
  Palette: Palette,
  Plane: Plane,
  RotateCcw: RotateCcw,
  Gift: Gift,
  Package: Package,
  HeartPlus: HeartPlus,
  HeartPulse: HeartPulse,
  TriangleAlert: TriangleAlert,
  HandCoins: HandCoins,
  LineChart: LineChart,
  SmilePlus: SmilePlus,
  Coins: Coins,
  CircleDollarSign: CircleDollarSign,
  TrendingUp: TrendingUp,
  Umbrella: Umbrella,
  Wallet: Wallet,
  Sprout: Sprout,
  Leaf: Leaf,
  MirrorRound: MirrorRound,
  BrushCleaning: BrushCleaning,
  DollarSign: DollarSign,
  Landmark: Landmark,
  Ticket: Ticket,
  Film: Film,
  Receipt: Receipt,
  Fuel: Fuel,
  BookOpen: BookOpen,
  TramFront: TramFront,
  Warehouse: Warehouse,
  LampDesk: LampDesk,
  Armchair: Armchair,
  Flower: Flower,
  Clover: Clover,
  Sun: Sun,
  Bug: Bug,
  School: School,
  Eraser: Eraser,
  Hammer: Hammer,
  Puzzle: Puzzle,
  PencilRuler: PencilRuler,
  Music: Music,
  Siren: Siren,
  Feather: Feather,
  ChefHat: ChefHat,
  Snowflake: Snowflake,
  AirVent: AirVent,
  Cat: Cat,
  TreePalm: TreePalm,
  Dices: Dices,
  Bubbles: Bubbles,
  Bird: Bird,
  KeySquare: KeySquare,
  Paintbrush: Paintbrush,
  Trees: Trees,
  Fish: Fish,
  SportShoe: SportShoe,
  Bath: Bath,
  ThermometerSnowflake: ThermometerSnowflake,
  Transgender: Transgender,
  WashingMachine: WashingMachine,
  MapPinned: MapPinned,
  ParkingCircle: ParkingCircle,
  Mail: Mail,
  Bus: Bus,
  Train: Train,
  Wifi: Wifi,
  Activity: Activity,
  HeartHandshake: HeartHandshake,
  Shield: Shield,
  Bell: Bell,
  Clock: Clock,
  Calendar: Calendar,
  Star: Star,
  CheckCircle: CheckCircle,
  Gem: Gem,
  Egg: Egg,
  GlassWater: GlassWater,
};
